#!/usr/bin/env bash

cat > /root/.bashrc_devcontainer <<'EOF'
# Auto-generated by devcontainer
if [ -f "/opt/miniforge/etc/profile.d/conda.sh" ]; then
  source "/opt/miniforge/etc/profile.d/conda.sh"
  conda activate adapters 2>/dev/null || true
fi

export CLASSPATH=$(/usr/local/hadoop/bin/hdfs classpath --glob 2>/dev/null || true)

# Colored prompt
export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

# Enable colored ls output
export LS_COLORS='rs=0:di=01;34:ln=01;36:ex=01;32:*.tar=01;31:*.zip=01;31'

# Aliases for colored output
alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lah --color=auto'
alias grep='grep --color=auto'
EOF

# Source it
source /root/.bashrc_devcontainer

# Add to .bashrc if not already there
if ! grep -q "source /root/.bashrc_devcontainer" /root/.bashrc 2>/dev/null; then
  echo "if [ -f /root/.bashrc_devcontainer ]; then source /root/.bashrc_devcontainer; fi" >> /root/.bashrc
fi

echo "Environment setup complete!"