name: Velox Test
run-name: ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
    inputs:
      repository: &repository
        description: 'Velox repository'
        type: string
        required: false
        default: 'facebookincubator/velox'
      velox_commit: &velox_commit
        description: 'Velox commit SHA or branch'
        type: string
        required: false
        default: 'main'
      build_target:
        description: 'Select the build target'
        type: choice
        required: false
        default: 'gpu'
        options:
          - all
          - cpu
          - gpu

  workflow_call:
    inputs:
      repository: *repository
      velox_commit: *velox_commit
      build_target:
        description: 'Select the build target'
        type: string
        required: false
        default: 'gpu'

defaults:
  run:
    shell: bash

jobs:
  velox-cpu:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'cpu' || github.event.inputs.build_target == 'all' || github.event.inputs.build_target == 'cpu' }}
    runs-on: linux-amd64-cpu4

    env:
      GH_TOKEN: ${{ github.token }}
      DOCKER_RUNTIME: runc

    steps:
      - &checkout-velox-testing
        name: Checkout this repository for CI scripts
        uses: actions/checkout@v4
        with:
          path: velox-testing

      - &checkout-velox
        name: Setup Velox
        uses: ./velox-testing/.github/actions/velox-setup
        with:
          repository: ${{ inputs.repository }}
          velox_commit: ${{ inputs.velox_commit }}

      - &load-deps
        name: Download and Load Velox Dependencies Container Image
        env:
          AWS_ARN_STRING: ${{ secrets.AWS_ARN_STRING }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ vars.S3_BUCKET_REGION }}
        run: |
          pushd ${{ github.workspace }}/velox-testing/velox/scripts
          ./fetch_centos_deps_image.sh
          popd
      - name: Building Velox for CPU
        run: |
          echo "   - CUDF support: DISABLED"
          echo "   - Target: CPU-only build"
          cd ${{ github.workspace }}/velox-testing/velox/scripts
          TREAT_WARNINGS_AS_ERRORS=0 ./build_velox.sh --all-cuda-archs --cpu --log build_velox_cpu.log

      - name: Upload velox_cpu_build_log as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: velox_cpu_build_log
          path: ${{ github.workspace }}/velox-testing/velox/scripts/build_velox_cpu.log

      - &run-velox-tests
        name: Run Velox CPU Tests
        working-directory: ${{ github.workspace }}/velox-testing/velox/scripts
        run: ./test_velox.sh --device-type cpu

  velox-gpu:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'gpu' || github.event.inputs.build_target == 'all' || github.event.inputs.build_target == 'gpu' }}
    runs-on: linux-amd64-gpu-l4-latest-1
    
    env:
      GH_TOKEN: ${{ github.token }}
      DOCKER_RUNTIME: nvidia

    steps:
      - *checkout-velox-testing

      - *checkout-velox

      - *load-deps

      - name: Building Velox for GPU
        working-directory: ${{ github.workspace }}/velox-testing/velox/scripts
        run: |
          echo "   - CUDF support: ENABLED"
          echo "   - Target: GPU-accelerated build"
          TREAT_WARNINGS_AS_ERRORS=0 ./build_velox.sh --all-cuda-archs --gpu --log build_velox_gpu.log

      - name: Upload velox_gpu_build_log as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: velox_gpu_build_log
          path: ${{ github.workspace }}/velox-testing/velox/scripts/build_velox_gpu.log

      - name: Run Velox GPU Tests
        working-directory: ${{ github.workspace }}/velox-testing/velox/scripts
        run: ./test_velox.sh --device-type gpu
